/**
 * The anchor contract (Landing-Redesign-Plan.md §3.1).
 *
 * The eye reads one continuous line across the act boundaries while the DOM
 * stays as small, separately understandable pieces. That is **not** because the
 * two sides of a seam are equal numbers — they cannot be. Each act is its own
 * coordinate box, so act *i* leaves at its own bottom edge (y = 1) and act
 * *i+1* enters at its own top edge (y = 0): the same *screen* point, different
 * numbers. The seam rule is that shape — an exit on the bottom edge, an enter
 * on the top edge, one shared horizontal fraction. `assertContinuity`
 * (`pathBuilders.ts`) checks it, but it is called from the test suite and from
 * nothing else — no runtime module calls it, so nothing checks this file at
 * load time. `anchors.test.ts` is what pins the values, and it has to: the
 * check is relative, so a coordinated edit that moves both sides of a seam
 * together passes it, and it is not defined over the acts that leave the
 * pattern on purpose (`origin`, whose exit is the fork point, and `doors`,
 * whose exit is the CTA node). `VERTICAL_CHAIN` is the sub-record it covers.
 *
 * **Frames.** x and y here are **act-local**: x runs 0..1 across one act's own
 * strip and y runs 0..1 down that act's own band. This is *not* the frame
 * `stationPositions` (station.ts) uses — its x is **track-local**, one station
 * per viewport, and its y is the constant walk baseline rather than an act
 * band — and it is not viewport coordinates either. The two are different
 * geometry, not one frame needing conversion: the vertical strand segments are
 * built from these anchors, the horizontal walk's rail from those station
 * positions, and how they compose on screen is a layout decision owned by the
 * Stage 2 caller. `pathFor` (Task 6) is frame-agnostic — it turns two points
 * *in one frame* into a path string and neither knows nor needs to know which
 * frame that is. Nothing should read these values as track widths.
 *
 * Kept in one place because both ends of every seam read from here.
 */

/** The acts, in scroll order. The single source of the act set and its order. */
export const ACT_ORDER = ['origin', 'pillars', 'way', 'proof', 'doors'] as const;

export type ActName = (typeof ACT_ORDER)[number];

export type Anchor = { x: number; y: number };

/** One act's strand endpoints. */
type AnchorPair = { enter: Anchor; exit: Anchor };

/**
 * Both endpoints of one act, frozen.
 *
 * `as const` is a compile-time promise only: at runtime an exported anchor is
 * an ordinary mutable object, so a helper that normalised one in place would
 * silently rewrite the global contract for the rest of the page's life. The
 * depth matters — freezing only the outer object leaves `enter` and `exit`
 * writable, which are the values that matter.
 */
function endpoints(enter: Anchor, exit: Anchor): AnchorPair {
  return Object.freeze({ enter: Object.freeze({ ...enter }), exit: Object.freeze({ ...exit }) });
}

/**
 * Where each act's strand enters and leaves, in **act-local** coordinates:
 * x is a fraction of one act's own width, y runs 0 (its top edge) to 1 (its
 * bottom edge). Not viewport coordinates, and not the track-local frame
 * `stationPositions` uses.
 *
 * **The contract is a shape, not an equality.** An act's `enter` sits on its
 * top edge and its `exit` on its bottom edge, and neighbouring acts agree on
 * their horizontal fraction — so the two sides of a seam are the same *screen*
 * point even though they are different *numbers*, because each is expressed in
 * its own act's box. `assertContinuity` (pathBuilders.ts) checks exactly that,
 * and reading it as `exit === enter` is what made the shipped version throw a
 * false alarm on correct geometry.
 *
 * Two acts leave the pattern on purpose:
 * - `origin.exit` is **the fork point**, above the fold at y = 0.85, where the
 *   single strand becomes N. The seeds it forks into sit at y = 1 and are
 *   generated by `seedAnchors` (frames.ts), which also asserts that seam.
 * - `doors.exit` is **the CTA node** at mid-band: the strand ends inside
 *   `FinalCTA` rather than leaving the page.
 *
 * `satisfies Record<ActName, …>` rather than `Record<string, …>`: it constrains
 * the *keys*, so a renamed or deleted act is a compile error.
 */
export const ACT_ANCHORS = Object.freeze({
  origin: endpoints(
    /** The strand enters the hero from the top-right. */
    { x: 0.72, y: 0 },
    /** The fork point: one strand becomes N, and the seeds hang below it. */
    { x: 0.5, y: 0.85 },
  ),
  pillars: endpoints(
    /** The act's envelope. The walk's rail is generated in its own frame by
     * `frames.ts`; this is the top edge the act's band starts from, and its
     * exit must agree with the ribbon's exit x (Task 2). */
    { x: 0.75, y: 0 },
    { x: 0.75, y: 1 },
  ),
  way: endpoints({ x: 0.75, y: 0 }, { x: 0.75, y: 1 }),
  proof: endpoints({ x: 0.75, y: 0 }, { x: 0.75, y: 1 }),
  doors: endpoints(
    { x: 0.75, y: 0 },
    /** The strand converges to a single point — the CTA node. */
    { x: 0.75, y: 0.5 },
  ),
} satisfies Record<ActName, AnchorPair>);

/**
 * The acts whose strand runs edge to edge through its own band, in scroll
 * order — the chain `assertContinuity` is defined over, and its default.
 *
 * `origin` is absent because it hands off through the fork rather than through
 * an edge: its exit is the fork point, so passing this whole record would throw
 * on a *correct* contract. The seams either side of it are the arity changes —
 * the fan (1→N, checked by `assertForkSeam`) and the ribbon's convergence
 * (N→1, checked by `assertRibbonSeam`), both in `frames.ts`.
 *
 * Built from `ACT_ANCHORS` by reference, not by copy: a seam that moves in one
 * place must move in both.
 */
export const VERTICAL_CHAIN = Object.freeze({
  pillars: ACT_ANCHORS.pillars,
  way: ACT_ANCHORS.way,
  proof: ACT_ANCHORS.proof,
  doors: ACT_ANCHORS.doors,
});
